"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowLeft, CheckCircle2, Smartphone, Search } from "lucide-react";
import { supabase } from "@/lib/supabase";

const TALLER_ID = 1;
const money = (n:number) => new Intl.NumberFormat("es-AR",{style:"currency",currency:"USD",maximumFractionDigits:2}).format(Number(n)||0);
type Producto={id:number;nombre:string;marca:string|null;modelo:string|null;costo:number;precio:number;stock_actual:number;activo:boolean};
type Cliente={id:number;nombre:string;telefono:string|null};
type Form={producto_id:string;cliente_id:string;modelo:string;capacidad:string;color:string;imei:string;numero_serie:string;salud_bateria:string;condicion:string;estado_fisico:string;garantia_dias:string;costo_usd:string;precio_usd:string;observaciones:string};
const initial:Form={producto_id:"",cliente_id:"",modelo:"",capacidad:"",color:"",imei:"",numero_serie:"",salud_bateria:"",condicion:"USADO",estado_fisico:"A",garantia_dias:"60",costo_usd:"",precio_usd:"",observaciones:""};

export default function VentasEquiposPage(){
 const router=useRouter(); const [productos,setProductos]=useState<Producto[]>([]); const [clientes,setClientes]=useState<Cliente[]>([]); const [q,setQ]=useState(""); const [form,setForm]=useState<Form>(initial); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState(""); const [ok,setOk]=useState("");
 useEffect(()=>{(async()=>{const [p,c]=await Promise.all([supabase.from("productos").select("id,nombre,marca,modelo,costo,precio,stock_actual,activo").eq("taller_id",TALLER_ID).eq("activo",true).order("nombre"),supabase.from("clientes").select("id,nombre,telefono").eq("taller_id",TALLER_ID).order("nombre")]);if(p.error||c.error)setError(p.error?.message||c.error?.message||"No se pudieron cargar los datos.");setProductos((p.data||[]) as Producto[]);setClientes((c.data||[]) as Cliente[]);setLoading(false)})()},[]);
 const producto=productos.find(p=>p.id===Number(form.producto_id)); const precio=Number(form.precio_usd)||0; const costo=Number(form.costo_usd)||Number(producto?.costo)||0; const ganancia=precio-costo; const set=(key:keyof Form,value:string)=>setForm(f=>({...f,[key]:value}));
 const guardar=async(e:React.FormEvent)=>{e.preventDefault();setError("");setOk("");if(!producto){setError("Seleccioná el equipo del inventario.");return}if(Number(producto.stock_actual)<1){setError("Ese equipo no tiene stock disponible.");return}if(!form.modelo.trim()){setError("Ingresá el modelo.");return}if(precio<=0){setError("Ingresá el precio de venta.");return}setSaving(true);try{
  const {data:venta,error:ve}=await supabase.from("ventas").insert({taller_id:TALLER_ID,cliente_id:form.cliente_id?Number(form.cliente_id):null,subtotal:precio,descuento:0,total:precio,ganancia:Math.max(ganancia,0),metodo_pago:"PENDIENTE",estado:"COMPLETADA",observaciones:form.observaciones.trim()||null}).select("id").single(); if(ve)throw new Error(ve.message);
  const {error:de}=await supabase.from("venta_detalles").insert({venta_id:venta.id,producto_id:producto.id,producto_nombre:producto.nombre,cantidad:1,costo_unitario:costo,precio_unitario:precio,subtotal:precio,ganancia:ganancia}); if(de)throw new Error(de.message);
  const {error:ee}=await supabase.from("ventas_equipos").insert({taller_id:TALLER_ID,venta_id:venta.id,producto_id:producto.id,cliente_id:form.cliente_id?Number(form.cliente_id):null,marca:producto.marca||"Apple",modelo:form.modelo.trim(),capacidad:form.capacidad.trim()||null,color:form.color.trim()||null,imei:form.imei.trim()||null,numero_serie:form.numero_serie.trim()||null,salud_bateria:form.salud_bateria?Number(form.salud_bateria):null,condicion:form.condicion,estado_fisico:form.estado_fisico||null,garantia_dias:Number(form.garantia_dias)||0,costo_usd:costo,precio_usd:precio,ganancia_usd:ganancia,observaciones:form.observaciones.trim()||null}); if(ee)throw new Error(ee.message);
  const {error:se}=await supabase.from("productos").update({stock_actual:Number(producto.stock_actual)-1}).eq("id",producto.id).eq("taller_id",TALLER_ID); if(se)throw new Error(se.message);
  await supabase.from("movimientos_stock").insert({taller_id:TALLER_ID,producto_id:producto.id,tipo:"SALIDA",cantidad:1,motivo:"Venta de equipo",referencia_tipo:"VENTA",referencia_id:venta.id,costo_unitario:costo});
  setOk("Venta #"+venta.id+" registrada. Stock actualizado.");setForm(initial);
 }catch(err){setError(err instanceof Error?err.message:"No se pudo registrar la venta.");}finally{setSaving(false)}};
 const filtrados=productos.filter(p=>Number(p.stock_actual)>0 && (p.nombre+" "+(p.marca||"")+" "+(p.modelo||"")).toLowerCase().includes(q.toLowerCase())).slice(0,20);
 return <main className="min-h-screen bg-[#f5f8f6] p-4 md:p-7"><div className="mx-auto max-w-6xl">
  <button onClick={()=>router.push("/ventas")} className="mb-5 flex items-center gap-2 text-sm font-bold text-gray-500"><ArrowLeft size={17}/> Ventas</button>
  <div className="mb-6 rounded-3xl bg-[#101815] p-6 text-white"><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-[#18a66b]"><Smartphone size={22}/></div><div><p className="text-xs font-black uppercase tracking-[.18em] text-white/50">Ventas de equipos</p><h1 className="text-2xl font-black">Nueva venta de iPhone / equipo</h1></div></div><p className="mt-3 text-sm text-white/60">Registrar IMEI, condición, batería, costo, precio y garantía junto con la venta.</p></div>
  {error&&<div className="mb-4 rounded-2xl border border-red-200 bg-red-50 p-4 text-sm font-semibold text-red-700">{error}</div>}{ok&&<div className="mb-4 flex items-center gap-2 rounded-2xl border border-green-200 bg-green-50 p-4 text-sm font-semibold text-green-700"><CheckCircle2 size={18}/>{ok}</div>}
  {loading?<div className="rounded-3xl bg-white p-8 text-center">Cargando...</div>:<form onSubmit={guardar} className="grid gap-6 lg:grid-cols-[1.3fr_.7fr]">
   <section className="rounded-3xl border bg-white p-5 shadow-sm md:p-7"><h2 className="text-lg font-black">1. Equipo</h2>
    <div className="relative mt-4"><Search className="absolute left-3 top-3 text-gray-400" size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar equipo con stock..." className="h-11 w-full rounded-xl border pl-10 pr-3"/></div>
    <select value={form.producto_id} onChange={e=>{const p=productos.find(x=>x.id===Number(e.target.value));set("producto_id",e.target.value);if(p){set("modelo",p.modelo||p.nombre);set("costo_usd",String(p.costo||""));set("precio_usd",String(p.precio||""))}}} className="mt-3 h-11 w-full rounded-xl border px-3"><option value="">Seleccionar equipo</option>{filtrados.map(p=><option key={p.id} value={p.id}>{p.nombre} — stock {p.stock_actual} — {money(p.precio)}</option>)}</select>
    <div className="mt-5 grid gap-3 md:grid-cols-2"><Field label="Modelo *" value={form.modelo} onChange={v=>set("modelo",v)}/><Field label="Capacidad" value={form.capacidad} onChange={v=>set("capacidad",v)} placeholder="128 GB"/><Field label="Color" value={form.color} onChange={v=>set("color",v)}/><Field label="IMEI" value={form.imei} onChange={v=>set("imei",v)}/><Field label="Número de serie" value={form.numero_serie} onChange={v=>set("numero_serie",v)}/><Field label="Salud de batería %" type="number" value={form.salud_bateria} onChange={v=>set("salud_bateria",v)}/><label className="text-sm font-bold">Condición<select value={form.condicion} onChange={e=>set("condicion",e.target.value)} className="mt-1 h-11 w-full rounded-xl border px-3 font-normal"><option>USADO</option><option>NUEVO</option></select></label><label className="text-sm font-bold">Estado físico<select value={form.estado_fisico} onChange={e=>set("estado_fisico",e.target.value)} className="mt-1 h-11 w-full rounded-xl border px-3 font-normal"><option>A</option><option>B</option><option>OUTLET</option></select></label><Field label="Garantía (días)" type="number" value={form.garantia_dias} onChange={v=>set("garantia_dias",v)}/><Field label="Observaciones" value={form.observaciones} onChange={v=>set("observaciones",v)}/></div>
    <label className="mt-4 block text-sm font-bold">Cliente<select value={form.cliente_id} onChange={e=>set("cliente_id",e.target.value)} className="mt-1 h-11 w-full rounded-xl border px-3 font-normal"><option value="">Consumidor final</option>{clientes.map(c=><option key={c.id} value={c.id}>{c.nombre} {c.telefono?"— "+c.telefono:""}</option>)}</select></label>
   </section>
   <aside className="h-fit rounded-3xl border bg-white p-5 shadow-sm md:p-7"><h2 className="text-lg font-black">2. Venta</h2><div className="mt-5 grid gap-3"><Field label="Costo USD" type="number" value={form.costo_usd} onChange={v=>set("costo_usd",v)}/><Field label="Precio de venta USD *" type="number" value={form.precio_usd} onChange={v=>set("precio_usd",v)}/></div><div className="mt-5 rounded-2xl bg-[#e9f8f1] p-5"><p className="text-xs font-bold text-gray-500">Ganancia</p><p className="mt-1 text-3xl font-black text-[#148f5c]">{money(ganancia)}</p></div><button disabled={saving} className="mt-5 flex h-12 w-full items-center justify-center rounded-xl bg-[#18a66b] text-sm font-black text-white disabled:opacity-60">{saving?"Registrando...":"Confirmar venta de equipo"}</button></aside>
  </form>}
 </div></main>
}
function Field({label,value,onChange,placeholder,type="text"}:{label:string;value:string;onChange:(v:string)=>void;placeholder?:string;type?:string}){return <label className="text-sm font-bold">{label}<input type={type} value={value} placeholder={placeholder} onChange={e=>onChange(e.target.value)} className="mt-1 h-11 w-full rounded-xl border px-3 font-normal"/></label>}
