-- TALLERES - PRESUPUESTO DE REPARACIONES
-- Ejecutar una sola vez en Supabase SQL Editor.
-- Los repuestos se reservan en el presupuesto, pero NO descuentan stock.
-- El stock se descuenta al iniciar la reparación mediante confirmar_reparacion_repuestos().

CREATE TABLE IF NOT EXISTS public.presupuesto_reparacion_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  taller_id bigint NOT NULL,
  orden_id bigint NOT NULL REFERENCES public.ordenes_reparacion(id) ON DELETE CASCADE,
  producto_id bigint NOT NULL REFERENCES public.productos(id),
  cantidad integer NOT NULL CHECK (cantidad > 0),
  costo_unitario numeric(12,2) NOT NULL DEFAULT 0,
  precio_unitario numeric(12,2) NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_presupuesto_reparacion_items_orden
  ON public.presupuesto_reparacion_items(orden_id);

ALTER TABLE public.presupuesto_reparacion_items ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "presupuesto_reparacion_items_anon_select" ON public.presupuesto_reparacion_items;
DROP POLICY IF EXISTS "presupuesto_reparacion_items_anon_insert" ON public.presupuesto_reparacion_items;
DROP POLICY IF EXISTS "presupuesto_reparacion_items_anon_update" ON public.presupuesto_reparacion_items;
DROP POLICY IF EXISTS "presupuesto_reparacion_items_anon_delete" ON public.presupuesto_reparacion_items;

CREATE POLICY "presupuesto_reparacion_items_anon_select"
ON public.presupuesto_reparacion_items FOR SELECT TO anon USING (true);

CREATE POLICY "presupuesto_reparacion_items_anon_insert"
ON public.presupuesto_reparacion_items FOR INSERT TO anon WITH CHECK (true);

CREATE POLICY "presupuesto_reparacion_items_anon_update"
ON public.presupuesto_reparacion_items FOR UPDATE TO anon USING (true) WITH CHECK (true);

CREATE POLICY "presupuesto_reparacion_items_anon_delete"
ON public.presupuesto_reparacion_items FOR DELETE TO anon USING (true);

-- Eliminar un presupuesto existente no toca stock porque todavía no fue utilizado.

-- Consume todos los repuestos presupuestados de una orden de forma atómica.
CREATE OR REPLACE FUNCTION public.confirmar_reparacion_repuestos(p_orden_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_item record;
  v_orden_taller_id bigint;
  v_producto public.productos%ROWTYPE;
BEGIN
  SELECT taller_id INTO v_orden_taller_id
  FROM public.ordenes_reparacion
  WHERE id = p_orden_id;

  IF v_orden_taller_id IS NULL THEN
    RAISE EXCEPTION 'La reparación no existe';
  END IF;

  FOR v_item IN
    SELECT * FROM public.presupuesto_reparacion_items
    WHERE orden_id = p_orden_id
    ORDER BY id
  LOOP
    SELECT * INTO v_producto
    FROM public.productos
    WHERE id = v_item.producto_id
      AND taller_id = v_orden_taller_id
      AND activo = true
    FOR UPDATE;

    IF NOT FOUND THEN
      RAISE EXCEPTION 'El producto % no existe o no pertenece al taller', v_item.producto_id;
    END IF;

    IF v_producto.stock_actual < v_item.cantidad THEN
      RAISE EXCEPTION 'Stock insuficiente para %. Disponible: %, solicitado: %', v_producto.nombre, v_producto.stock_actual, v_item.cantidad;
    END IF;

    UPDATE public.productos
    SET stock_actual = stock_actual - v_item.cantidad
    WHERE id = v_item.producto_id;

    INSERT INTO public.reparacion_repuestos (
      taller_id, orden_id, producto_id, cantidad, costo_unitario
    ) VALUES (
      v_orden_taller_id, p_orden_id, v_item.producto_id, v_item.cantidad,
      COALESCE(v_item.costo_unitario, v_producto.costo, 0)
    );

    INSERT INTO public.movimientos_stock (
      taller_id, producto_id, tipo, cantidad, motivo,
      referencia_tipo, referencia_id, costo_unitario
    ) VALUES (
      v_orden_taller_id, v_item.producto_id, 'SALIDA', v_item.cantidad,
      'Repuesto utilizado en reparación', 'REPARACION', p_orden_id,
      COALESCE(v_item.costo_unitario, v_producto.costo, 0)
    );
  END LOOP;
END;
$$;

GRANT EXECUTE ON FUNCTION public.confirmar_reparacion_repuestos(bigint) TO anon;
GRANT EXECUTE ON FUNCTION public.confirmar_reparacion_repuestos(bigint) TO authenticated;

SELECT 'presupuesto_reparacion listo' AS estado;
