-- TALLERES - REPUESTOS USADOS EN REPARACIONES
-- Ejecutar una sola vez en Supabase SQL Editor.

CREATE TABLE IF NOT EXISTS public.reparacion_repuestos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  taller_id bigint NOT NULL,
  orden_id bigint NOT NULL REFERENCES public.ordenes_reparacion(id) ON DELETE CASCADE,
  producto_id bigint NOT NULL REFERENCES public.productos(id),
  cantidad integer NOT NULL CHECK (cantidad > 0),
  costo_unitario numeric(12,2) NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_reparacion_repuestos_orden
  ON public.reparacion_repuestos(orden_id);

CREATE INDEX IF NOT EXISTS idx_reparacion_repuestos_producto
  ON public.reparacion_repuestos(producto_id);

ALTER TABLE public.reparacion_repuestos ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "reparacion_repuestos_anon_select" ON public.reparacion_repuestos;
DROP POLICY IF EXISTS "reparacion_repuestos_anon_insert" ON public.reparacion_repuestos;

CREATE POLICY "reparacion_repuestos_anon_select"
ON public.reparacion_repuestos
FOR SELECT TO anon
USING (true);

CREATE POLICY "reparacion_repuestos_anon_insert"
ON public.reparacion_repuestos
FOR INSERT TO anon
WITH CHECK (true);

-- Uso atómico de un repuesto:
-- 1) verifica stock,
-- 2) descuenta stock_actual,
-- 3) registra el repuesto en la reparación,
-- 4) registra la SALIDA en movimientos_stock.
CREATE OR REPLACE FUNCTION public.usar_repuesto_reparacion(
  p_orden_id bigint,
  p_producto_id bigint,
  p_cantidad integer
)
RETURNS public.reparacion_repuestos
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_orden_taller_id bigint;
  v_producto public.productos%ROWTYPE;
  v_result public.reparacion_repuestos;
BEGIN
  IF p_cantidad IS NULL OR p_cantidad <= 0 THEN
    RAISE EXCEPTION 'La cantidad debe ser mayor a 0';
  END IF;

  SELECT taller_id
    INTO v_orden_taller_id
  FROM public.ordenes_reparacion
  WHERE id = p_orden_id;

  IF v_orden_taller_id IS NULL THEN
    RAISE EXCEPTION 'La reparación no existe';
  END IF;

  SELECT *
    INTO v_producto
  FROM public.productos
  WHERE id = p_producto_id
    AND taller_id = v_orden_taller_id
    AND activo = true
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'El producto no existe o no pertenece al taller de la reparación';
  END IF;

  IF v_producto.stock_actual < p_cantidad THEN
    RAISE EXCEPTION 'Stock insuficiente. Disponible: %, solicitado: %', v_producto.stock_actual, p_cantidad;
  END IF;

  UPDATE public.productos
  SET stock_actual = stock_actual - p_cantidad
  WHERE id = p_producto_id;

  INSERT INTO public.reparacion_repuestos (
    taller_id,
    orden_id,
    producto_id,
    cantidad,
    costo_unitario
  )
  VALUES (
    v_orden_taller_id,
    p_orden_id,
    p_producto_id,
    p_cantidad,
    COALESCE(v_producto.costo, 0)
  )
  RETURNING * INTO v_result;

  INSERT INTO public.movimientos_stock (
    taller_id,
    producto_id,
    tipo,
    cantidad,
    motivo,
    referencia_tipo,
    referencia_id,
    costo_unitario
  )
  VALUES (
    v_orden_taller_id,
    p_producto_id,
    'SALIDA',
    p_cantidad,
    'Repuesto utilizado en reparación',
    'REPARACION',
    p_orden_id,
    COALESCE(v_producto.costo, 0)
  );

  RETURN v_result;
END;
$$;

GRANT EXECUTE ON FUNCTION public.usar_repuesto_reparacion(bigint, bigint, integer) TO anon;
GRANT EXECUTE ON FUNCTION public.usar_repuesto_reparacion(bigint, bigint, integer) TO authenticated;

SELECT 'reparacion_repuestos listo' AS estado;
