"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowLeft, BarChart3, CheckCircle2, Clock3, DollarSign, Package, RefreshCw, Wrench, Users } from "lucide-react";
import { supabase } from "../../lib/supabase";

type Orden={id:number;estado:string|null;created_at:string|null;presupuesto_mano_obra:number|null;cliente_id:number|null};
type Item={orden_id:number;cantidad:number;precio_unitario:number;costo_unitario:number};

const money=(n:number)=>n.toLocaleString("es-AR",{style:"currency",currency:"ARS",maximumFractionDigits:0});
const startOf=(days:number)=>{const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()-days+1);return d.toISOString();};

export default function ReportesPage(){
 const router=useRouter(); const [periodo,setPeriodo]=useState("30"); const [ordenes,setOrdenes]=useState<Orden[]>([]); const [items,setItems]=useState<Item[]>([]); const [ventas,setVentas]=useState<any[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
 const cargar=async()=>{setLoading(true);setError("");const desde=periodo==="all"?"2000-01-01T00:00:00.000Z":startOf(Number(periodo));const [o,i,v]=await Promise.all([
  supabase.from("ordenes_reparacion").select("id,estado,created_at,presupuesto_mano_obra,cliente_id").gte("created_at",desde),
  supabase.from("presupuesto_reparacion_items").select("orden_id,cantidad,precio_unitario,costo_unitario"),
  supabase.from("ventas").select("total,created_at,anulada").gte("created_at",desde)
 ]);if(o.error||i.error||v.error)setError(o.error?.message||i.error?.message||v.error?.message||"No se pudieron cargar los reportes.");else{setOrdenes((o.data||[]) as any);setItems((i.data||[]) as any);setVentas(v.data||[]);}setLoading(false)};
 useEffect(()=>{cargar()},[periodo]);
 const stats=useMemo(()=>{const reparaciones=ordenes.length;const entregadas=ordenes.filter(o=>String(o.estado).toUpperCase()==="ENTREGADO").length;const abiertas=ordenes.filter(o=>!["ENTREGADO","CANCELADO"].includes(String(o.estado).toUpperCase())).length;const presupuestos=ordenes.reduce((s,o)=>s+Number(o.presupuesto_mano_obra||0),0)+items.filter(i=>ordenes.some(o=>o.id===i.orden_id)).reduce((s,i)=>s+Number(i.cantidad)*Number(i.precio_unitario),0);const costo=items.filter(i=>ordenes.some(o=>o.id===i.orden_id)).reduce((s,i)=>s+Number(i.cantidad)*Number(i.costo_unitario||0),0);const venta=ventas.filter(v=>!v.anulada).reduce((s,v)=>s+Number(v.total||0),0);return{reparaciones,entregadas,abiertas,presupuestos,costo,venta,ganancia:presupuestos-costo};},[ordenes,items,ventas]);
 const estados=useMemo(()=>{const m:Record<string,number>={};ordenes.forEach(o=>{const e=o.estado||"SIN ESTADO";m[e]=(m[e]||0)+1});return Object.entries(m).sort((a,b)=>b[1]-a[1]);},[ordenes]);
 return <main className="min-h-screen bg-[#f7f8f7] px-4 py-5 md:px-7 md:py-7"><div className="mx-auto max-w-[1400px]"><div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-black uppercase tracking-[.2em] text-green-700">Administración</p><h1 className="mt-1 text-3xl font-black">Reportes</h1><p className="mt-2 text-sm text-gray-500">Resumen operativo y económico del taller.</p></div><div className="flex gap-2"><button onClick={()=>router.push("/")} className="rounded-xl border bg-white px-4 py-3 text-sm font-bold"><ArrowLeft size={16} className="mr-2 inline"/>Inicio</button><button onClick={cargar} className="rounded-xl border bg-white px-4 py-3 text-sm font-bold"><RefreshCw size={16} className="mr-2 inline"/>Actualizar</button></div></div>
 <div className="mt-5 flex flex-wrap gap-2">{[["7","7 días"],["30","30 días"],["90","90 días"],["all","Todo"]].map(([v,l])=><button key={v} onClick={()=>setPeriodo(v)} className={"rounded-xl px-4 py-2.5 text-sm font-bold "+(periodo===v?"bg-green-600 text-white":"border bg-white text-gray-600")}>{l}</button>)}</div>
 {error&&<div className="mt-4 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
 {loading?<div className="mt-5 rounded-2xl border bg-white p-12 text-center text-sm text-gray-500">Cargando reportes...</div>:<><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Card icon={<Wrench size={19}/>} t="Reparaciones" v={stats.reparaciones}/><Card icon={<CheckCircle2 size={19}/>} t="Entregadas" v={stats.entregadas}/><Card icon={<Clock3 size={19}/>} t="Abiertas" v={stats.abiertas}/><Card icon={<Users size={19}/>} t="Clientes atendidos" v={new Set(ordenes.map(o=>o.cliente_id).filter(Boolean)).size}/></div>
 <div className="mt-3 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MoneyCard icon={<DollarSign size={19}/>} t="Presupuestado" v={stats.presupuestos}/><MoneyCard icon={<Package size={19}/>} t="Costo repuestos" v={stats.costo}/><MoneyCard icon={<DollarSign size={19}/>} t="Ventas registradas" v={stats.venta}/><MoneyCard icon={<BarChart3 size={19}/>} t="Margen estimado" v={stats.ganancia}/></div>
 <div className="mt-5 grid gap-5 lg:grid-cols-2"><section className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="font-black">Reparaciones por estado</h2><div className="mt-4 space-y-3">{estados.length?estados.map(([e,n])=><div key={e}><div className="mb-1 flex justify-between text-sm"><span>{e}</span><b>{n}</b></div><div className="h-2 overflow-hidden rounded-full bg-gray-100"><div className="h-full rounded-full bg-green-500" style={{width:Math.max(4,n/Math.max(stats.reparaciones,1)*100)+"%"}}/></div></div>):<p className="text-sm text-gray-500">Sin datos.</p>}</div></section><section className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="font-black">Resumen</h2><div className="mt-4 space-y-3 text-sm"><Row t="Presupuestos generados" v={ordenes.filter(o=>Number(o.presupuesto_mano_obra||0)>0||items.some(i=>i.orden_id===o.id)).length}/><Row t="Repuestos utilizados/presupuestados" v={items.filter(i=>ordenes.some(o=>o.id===i.orden_id)).reduce((s,i)=>s+Number(i.cantidad),0)}/><Row t="Órdenes canceladas" v={ordenes.filter(o=>String(o.estado).toUpperCase()==="CANCELADO").length}/><Row t="Ticket promedio presupuestado" v={stats.reparaciones?money(stats.presupuestos/stats.reparaciones):money(0)}/></div></section></div></>}</div></main>;
}
function Card({icon,t,v}:{icon:any;t:string;v:number}){return <div className="rounded-2xl border bg-white p-5 shadow-sm"><div className="text-green-700">{icon}</div><p className="mt-3 text-2xl font-black">{v}</p><p className="text-xs text-gray-500">{t}</p></div>}
function MoneyCard({icon,t,v}:{icon:any;t:string;v:number}){return <div className="rounded-2xl border bg-white p-5 shadow-sm"><div className="text-green-700">{icon}</div><p className="mt-3 text-xl font-black">{money(v)}</p><p className="text-xs text-gray-500">{t}</p></div>}
function Row({t,v}:{t:string;v:any}){return <div className="flex items-center justify-between border-b border-gray-100 pb-3"><span className="text-gray-500">{t}</span><b>{v}</b></div>}
