"use client";

import { useEffect,useState } from "react";
import { useParams,useRouter } from "next/navigation";
import { ArrowLeft,Home,Printer } from "lucide-react";
import { supabase } from "../../../../lib/supabase";

type Cliente={nombre:string|null;dni:string|null;telefono:string|null};
type Equipo={marca:string|null;modelo:string|null;imei:string|null;numero_serie:string|null;color:string|null;capacidad:string|null;bateria_porcentaje:number|null};
type Orden={id:number;estado:string|null;falla_reportada:string|null;observaciones:string|null;created_at:string|null;cliente:Cliente|null;equipo:Equipo|null};
type Fila={categoria:string;prueba:string;estado:string;observacion:string|null};
type Item={cantidad:number;precio_unitario:number|null};
type Pago={monto:number|null;monto_usd:number|null;metodo_pago:string|null;fecha_pago:string};

const normal=(v:string|null|undefined)=>(v||"").toUpperCase().replaceAll("_"," ");
const estadoTexto=(v:string)=>{const x=normal(v);if(x==="FUNCIONA")return"OK";if(x==="NO FUNCIONA")return"NO FUNCIONA";if(x==="NO PROBADO")return"NO PROBADO";return v};
const fecha=(v:string|null)=>v?new Date(v).toLocaleString("es-AR",{dateStyle:"medium",timeStyle:"short"}):"-";

export default function ComprobanteRecepcion(){
 const params=useParams();const router=useRouter();const id=Number(params.id);
 const[orden,setOrden]=useState<Orden|null>(null),[check,setCheck]=useState<Fila[]>([]),[items,setItems]=useState<Item[]>([]),[pagos,setPagos]=useState<Pago[]>([]),[cargando,setCargando]=useState(true),[error,setError]=useState("");
 useEffect(()=>{(async()=>{const r=await supabase.from("ordenes_reparacion").select("id,estado,falla_reportada,observaciones,created_at,clientes(nombre,dni,telefono),equipos(marca,modelo,imei,numero_serie,color,capacidad,bateria_porcentaje)").eq("id",id).maybeSingle();if(r.error||!r.data){setError(r.error?.message||"No se encontró la orden.");setCargando(false);return}const o=r.data as any;setOrden({...o,cliente:Array.isArray(o.clientes)?o.clientes[0]||null:o.clientes||null,equipo:Array.isArray(o.equipos)?o.equipos[0]||null:o.equipos||null});const c=await supabase.from("checklist_reparacion").select("categoria,prueba,estado,observacion").eq("orden_id",id).eq("momento","ENTRADA").order("orden_prueba");if(!c.error)setCheck((c.data||[]) as Fila[]);const i=await supabase.from("presupuesto_reparacion_items").select("cantidad,precio_unitario").eq("orden_id",id);if(!i.error)setItems((i.data||[]) as Item[]);const p=await supabase.from("pagos_reparacion").select("monto,monto_usd,metodo_pago,fecha_pago").eq("orden_id",id).order("fecha_pago");if(!p.error)setPagos((p.data||[]) as Pago[]);setCargando(false)})()},[id]);
 if(cargando)return <main className="min-h-screen grid place-items-center text-sm text-gray-500">Cargando comprobante...</main>;
 if(!orden)return <main className="p-8"><p className="text-red-600">{error}</p></main>;
 const fisico=check.filter(x=>x.categoria==="Estado físico"),func=check.filter(x=>x.categoria==="Pruebas funcionales"),con=check.filter(x=>x.categoria==="Conectividad"),acc=check.filter(x=>x.categoria==="Accesorios"); const totalRepuestos=items.reduce((s,x)=>s+Number(x.cantidad||0)*Number(x.precio_unitario||0),0); const total=totalRepuestos; const abonado=pagos.reduce((s,x)=>s+Number(x.monto??x.monto_usd??0),0); const saldo=Math.max(total-abonado,0); const dinero=(n:number)=>n.toLocaleString("es-AR",{style:"currency",currency:"ARS",maximumFractionDigits:0});
 return <main className="min-h-screen bg-gray-100 p-4 print:bg-white print:p-0"><div className="mx-auto mb-4 flex max-w-[850px] gap-2 print:hidden"><button onClick={()=>router.push("/reparaciones/"+id)} className="rounded-xl border bg-white px-4 py-2 text-sm font-bold"><ArrowLeft size={16} className="mr-2 inline"/>Volver</button><button onClick={()=>router.push("/")} className="rounded-xl border bg-white px-4 py-2 text-sm font-bold"><Home size={16} className="mr-2 inline"/>Inicio</button><button onClick={()=>window.print()} className="rounded-xl bg-black px-4 py-2 text-sm font-bold text-white"><Printer size={16} className="mr-2 inline"/>Imprimir</button></div>
 <article className="mx-auto max-w-[850px] bg-white p-7 text-[11px] leading-4 text-gray-900 shadow-sm print:max-w-none print:p-6 print:shadow-none">
  <header className="border-b-2 border-black pb-4"><div className="flex items-start justify-between gap-5"><div><div className="text-3xl font-black tracking-tight text-black">BITFIX</div><p className="mt-1 font-bold uppercase tracking-widest">Orden de reparación</p><p className="text-gray-500">Comprobante de recepción</p></div><div className="text-right"><p className="text-[10px] uppercase text-gray-500">N° de orden</p><p className="text-2xl font-black">#{String(orden.id).padStart(5,"0")}</p><p>{fecha(orden.created_at)}</p></div></div></header>
  <section className="mt-4 grid grid-cols-2 gap-4"><Box title="CLIENTE"><b>{orden.cliente?.nombre||"-"}</b><br/>DNI: {orden.cliente?.dni||"-"}<br/>Teléfono: {orden.cliente?.telefono||"-"}</Box><Box title="EQUIPO"><b>{[orden.equipo?.marca,orden.equipo?.modelo].filter(Boolean).join(" ")||"-"}</b><br/>IMEI: {orden.equipo?.imei||"-"}<br/>Serie: {orden.equipo?.numero_serie||"-"}<br/>Color: {orden.equipo?.color||"-"} · {orden.equipo?.capacidad||"-"} · Batería: {orden.equipo?.bateria_porcentaje!=null?orden.equipo.bateria_porcentaje+"%":"-"}</Box></section>
  <section className="mt-4 rounded-lg border p-3"><b>PROBLEMA INFORMADO POR EL CLIENTE</b><p className="mt-1 whitespace-pre-wrap">{orden.falla_reportada||"-"}</p></section>
  {fisico.length>0&&<Checklist title="ESTADO FÍSICO" rows={fisico}/>}
  {func.length>0&&<Checklist title="PRUEBAS FUNCIONALES" rows={func}/>}
  {con.length>0&&<Checklist title="CONECTIVIDAD" rows={con}/>}
  {acc.length>0&&<Checklist title="ACCESORIOS RECIBIDOS" rows={acc}/>}
  <section className="mt-4 rounded-lg border p-3"><b>OBSERVACIONES</b><p className="mt-1 min-h-10 whitespace-pre-wrap">{orden.observaciones||"Sin observaciones."}</p></section>
  <section className="mt-5 break-inside-avoid rounded-lg border-2 border-black p-4"><div className="flex items-center justify-between border-b pb-2"><div><p className="text-[10px] font-black tracking-widest">BITFIX</p><h2 className="text-base font-black">COMPROBANTE DE ENTREGA</h2></div><div className="text-right"><p className="text-[9px] text-gray-500">ORDEN</p><p className="text-lg font-black">#{String(orden.id).padStart(5,"0")}</p></div></div><div className="mt-3 grid grid-cols-3 gap-3 text-right"><div><p className="text-[9px] text-gray-500">TOTAL</p><p className="text-lg font-black">{dinero(total)}</p></div><div><p className="text-[9px] text-gray-500">ABONADO</p><p className="text-lg font-black">{dinero(abonado)}</p></div><div><p className="text-[9px] text-gray-500">SALDO</p><p className="text-lg font-black">{dinero(saldo)}</p></div></div><div className="mt-3 border-t pt-3 text-[10px]"><p><b>Forma de pago:</b> {pagos.length?Array.from(new Set(pagos.map(p=>p.metodo_pago).filter(Boolean))).join(", "):"Pendiente"}</p><p><b>Estado:</b> {normal(orden.estado)}</p><p><b>Fecha:</b> {fecha(new Date().toISOString())}</p></div></section>
  <section className="mt-5 break-inside-avoid"><h2 className="border-b border-black pb-1 text-xs font-black">TÉRMINOS & CONDICIONES</h2><div className="mt-2 space-y-1 text-[9.5px] leading-[1.35]">
<p><b>Recepción:</b> Los dispositivos que ingresan apagados/sin imagen, no inicien o no se puedan evaluar en su totalidad las funciones básicas de los mismos. No tendrán garantía ni derecho a reclamo sobre partes que no pudieron ser puestas a prueba.</p>
<p>El cliente debe dar la clave de acceso al equipo para probar sus funciones como también garantizar tener acceso a su Apple ID, de lo contrario no se podrá dar garantía por ninguna de sus funciones ni tendrá derecho a reclamo por cualquier tipo de bloqueo que se produzca durante o luego de cualquier reparación.</p>
<p>Todo dispositivo, NO debe contener tarjeta SIM/funda. De lo contrario no se reconocerá el extravío de las mismas.</p>
<p><b>Garantía I:</b> La misma tendrá una duración de 90 días, iniciando en la fecha de entrega de dicho dispositivo. Para validar esta, los repuestos instalados deberán encontrarse en óptimo estado.</p>
<p><b>Garantía II:</b> La misma no tendrá validez, en caso de daños accidentales y/o manipulación del dispositivo por cualquier persona ajena a BITFIX.</p>
<p><b>Dispositivos mojados:</b> No tendrán garantía alguna sobre ningún tipo de reparación. Debido a que, la corrosión suele generar efectos adversos. No solo a corto plazo, sino también a futuro. Puede que el dispositivo no encienda nuevamente.</p>
<p><b>Datos del usuario:</b> BITFIX no se responsabiliza por la pérdida de información del cliente. Contactos, fotos o cuentas. Recuerde siempre realizar un respaldo de su información vital.</p>
<p><b>Reparaciones de placa:</b> En toda reparación de este índole, el dispositivo puede sufrir el riesgo de no encender nuevamente. Esto, debido a cuestiones circunstanciales y de contexto técnico.</p>
<p><b>Glass:</b> Durante el proceso, puede dañarse la pantalla. No correrá por nuestra cuenta el costo de los mismos. Pueden quedar mínimas burbujas, desniveles e incluso rayones producto del vidrio astillado. Este trabajo NO TIENE GARANTÍA, ya que son pantallas golpeadas.</p>
<p><b>Plazo de retiro:</b> Todo dispositivo que no sea retirado por su propietario, en un plazo máximo de 90 días, será considerado abandono, bajo el término 2525/2526 del Código Civil, quedando facultado el destino que se considere pertinente.</p>
<p>BITFIX no se responsabilizará ante una interpretación errónea por parte del cliente, en cualquier etapa de las anteriormente mencionadas. El cliente, al entregar su dispositivo y firmar este documento, acepta las condiciones anteriormente mencionadas.</p>
</div></section>
  <div className="mt-7 grid grid-cols-2 gap-10 border-t pt-7"><div><div className="h-10 border-b border-gray-500"></div><p className="mt-1 text-center">Firma del cliente</p></div><div><div className="h-10 border-b border-gray-500"></div><p className="mt-1 text-center">BITFIX</p></div></div>
  <footer className="mt-5 border-t pt-3 text-center text-[9px] text-gray-400">BITFIX · Comprobante de recepción · Orden #{String(orden.id).padStart(5,"0")}</footer>
 </article></main>;
}
function Box({title,children}:{title:string;children:any}){return <div className="rounded-lg border p-3"><p className="mb-1 text-[9px] font-black tracking-widest text-black">{title}</p>{children}</div>}
function Checklist({title,rows}:{title:string;rows:Fila[]}){return <section className="mt-4"><h2 className="mb-2 text-[10px] font-black tracking-widest text-black">{title}</h2><div className="grid grid-cols-2 gap-x-6 gap-y-1 rounded-lg border p-3 sm:grid-cols-3">{rows.map((r,i)=><div key={i} className="flex justify-between gap-2 border-b border-gray-100 pb-1"><span>{r.prueba}</span><b>{estadoTexto(r.estado)}</b></div>)}</div></section>}
