"use client";

import { useEffect,useMemo,useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowLeft,Plus,Search,Trash2,UserRound,Smartphone,CheckCircle2,Printer,MessageCircle } from "lucide-react";
import { supabase } from "../../../lib/supabase";

type Cliente={id:number;nombre:string;telefono:string|null}; type Equipo={id:number;cliente_id:number;marca:string|null;modelo:string|null;imei:string|null}; type Producto={id:number;nombre:string;precio:number|null;costo:number|null;stock_actual:number|null}; type Linea={producto_id:number;nombre:string;cantidad:number;precio:number;costo:number};
const money=(n:number)=>new Intl.NumberFormat("es-AR",{style:"currency",currency:"USD",maximumFractionDigits:2}).format(Number(n)||0);

export default function NuevoPresupuesto(){
 const router=useRouter();const [clientes,setClientes]=useState<Cliente[]>([]),[equipos,setEquipos]=useState<Equipo[]>([]),[productos,setProductos]=useState<Producto[]>([]);
 const [cliente,setCliente]=useState<Cliente|null>(null),[equipo,setEquipo]=useState<Equipo|null>(null),[q,setQ]=useState(""),[pq,setPq]=useState("");
 const [nuevo,setNuevo]=useState(false),[nombre,setNombre]=useState(""),[telefono,setTelefono]=useState(""),[modelo,setModelo]=useState(""),[imei,setImei]=useState("");
 const [servicio,setServicio]=useState(""),[mano,setMano]=useState(""),[validez,setValidez]=useState("7 días"),[lineas,setLineas]=useState<Linea[]>([]),[error,setError]=useState(""),[guardando,setGuardando]=useState(false),[creado,setCreado]=useState<number|null>(null);
 useEffect(()=>{supabase.from("clientes").select("id,nombre,telefono").order("nombre").then(r=>setClientes((r.data||[]) as Cliente[]));supabase.from("productos").select("id,nombre,precio,costo,stock_actual").eq("activo",true).order("nombre").then(r=>setProductos((r.data||[]) as Producto[]));},[]);
 useEffect(()=>{if(cliente)supabase.from("equipos").select("id,cliente_id,marca,modelo,imei").eq("cliente_id",cliente.id).order("modelo").then(r=>setEquipos((r.data||[]) as Equipo[]));else setEquipos([])},[cliente]);
 const cf=useMemo(()=>clientes.filter(c=>`${c.nombre} ${c.telefono||""}`.toLowerCase().includes(q.toLowerCase())).slice(0,8),[clientes,q]); const pf=useMemo(()=>productos.filter(p=>p.nombre.toLowerCase().includes(pq.toLowerCase())).slice(0,8),[productos,pq]); const total=lineas.reduce((s,l)=>s+l.cantidad*l.precio,0)+Number(mano||0);
 const add=(p:Producto)=>{const x=lineas.find(l=>l.producto_id===p.id);setLineas(x?lineas.map(l=>l.producto_id===p.id?{...l,cantidad:l.cantidad+1}:l):[...lineas,{producto_id:p.id,nombre:p.nombre,cantidad:1,precio:Number(p.precio||0),costo:Number(p.costo||0)}]);setPq("")};
 const guardar=async()=>{setError("");if(!nombre.trim()){setError("Ingresá el cliente.");return}if(!modelo.trim()&&!equipo){setError("Seleccioná o ingresá el equipo.");return}if(!servicio.trim()&&lineas.length===0&&Number(mano||0)<=0){setError("Agregá un concepto.");return}setGuardando(true);try{let c=cliente;if(!c){const r=await supabase.from("clientes").insert({taller_id:1,nombre:nombre.trim(),telefono:telefono.trim()||null}).select("id,nombre,telefono").single();if(r.error)throw r.error;c=r.data as Cliente}let e=equipo;if(!e){const r=await supabase.from("equipos").insert({taller_id:1,cliente_id:c.id,tipo:"CELULAR",marca:"Apple",modelo:modelo.trim(),imei:imei.trim()||null}).select("id,cliente_id,marca,modelo,imei").single();if(r.error)throw r.error;e=r.data as Equipo}const r=await supabase.from("presupuestos_independientes").insert({taller_id:1,cliente_id:c.id,equipo_id:e.id,servicio:servicio.trim()||null,mano_obra:Number(mano||0),validez,validez_dias:Number(validez.split(" ")[0]),total}).select("id").single();if(r.error)throw r.error;for(const l of lineas){const x=await supabase.from("presupuestos_independientes_items").insert({presupuesto_id:r.data.id,producto_id:l.producto_id,nombre_producto:l.nombre,cantidad:l.cantidad,precio_unitario:l.precio,costo_unitario:l.costo});if(x.error)throw x.error}setCreado(r.data.id)}catch(e:any){setError(e.message||"No se pudo crear.")}finally{setGuardando(false)}};
 if(creado)return <main className="min-h-screen bg-[#f7f8f7] p-6"><div className="mx-auto max-w-xl rounded-3xl border bg-white p-8 text-center shadow-sm"><CheckCircle2 className="mx-auto text-green-600" size={48}/><h1 className="mt-4 text-2xl font-black">Presupuesto creado</h1><p className="mt-2 text-sm text-gray-500">Presupuesto #{creado} generado correctamente. No se descontó inventario.</p><div className="mt-6 flex flex-wrap justify-center gap-3"><button onClick={()=>window.print()} className="rounded-xl border px-5 py-3 font-bold"><Printer size={17} className="mr-2 inline"/>Imprimir</button><button onClick={()=>{const t=`Presupuesto #${creado} - Total ${money(total)}. Validez: ${validez}`;window.open(`https://wa.me/?text=${encodeURIComponent(t)}`,"_blank")}} className="rounded-xl bg-green-600 px-5 py-3 font-bold text-white"><MessageCircle size={17} className="mr-2 inline"/>WhatsApp</button><button onClick={()=>router.push("/presupuestos")} className="rounded-xl border px-5 py-3 font-bold">Volver</button></div></div></main>;
 return <main className="min-h-screen bg-[#f7f8f7] px-4 py-6 md:px-7"><div className="mx-auto max-w-1050px"><button onClick={()=>router.push("/presupuestos")} className="mb-5 flex items-center gap-2 text-sm font-bold text-gray-500"><ArrowLeft size={17}/> Presupuestos</button><div className="rounded-3xl border bg-white shadow-sm"><div className="border-b bg-gradient-to-r from-green-50 to-white p-6 md:p-8"><p className="text-xs font-black uppercase tracking-[.2em] text-green-700">Presupuesto independiente</p><h1 className="mt-1 text-3xl font-black">Nuevo presupuesto</h1><p className="mt-2 text-sm text-gray-500">No crea una reparación ni descuenta inventario.</p></div><div className="p-5 md:p-8">
 <h2 className="font-black">1. Cliente</h2><div className="relative mt-3"><Search className="absolute left-3 top-3 text-gray-400" size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar cliente por nombre o teléfono..." className="h-11 w-full rounded-xl border bg-gray-50 pl-10 pr-3"/>{!cliente&&q&&<div className="absolute z-20 mt-1 w-full rounded-xl border bg-white p-2 shadow-xl">{cf.map(c=><button key={c.id} onClick={()=>{setCliente(c);setNombre(c.nombre);setTelefono(c.telefono||"")}} className="flex w-full gap-3 rounded-lg p-3 text-left hover:bg-green-50"><UserRound size={17}/><span><b>{c.nombre}</b><small className="ml-2 text-gray-500">{c.telefono||""}</small></span></button>)}</div>}</div>{!cliente&&<button onClick={()=>setNuevo(true)} className="mt-3 text-sm font-bold text-green-700"><Plus size={15} className="inline"/> Crear cliente</button>}{nuevo&&<div className="mt-3 grid gap-3 md:grid-cols-2"><input value={nombre} onChange={e=>setNombre(e.target.value)} placeholder="Nombre *" className="rounded-xl border px-4 py-3"/><input value={telefono} onChange={e=>setTelefono(e.target.value)} placeholder="Teléfono" className="rounded-xl border px-4 py-3"/></div>}{cliente&&<div className="mt-3 rounded-xl bg-green-50 p-4 text-sm"><b>{cliente.nombre}</b> · {cliente.telefono||"Sin teléfono"} <button onClick={()=>setCliente(null)} className="ml-3 font-bold text-green-700">Cambiar</button></div>}
 <h2 className="mt-7 border-t pt-7 font-black">2. Equipo</h2>{cliente&&equipos.length>0&&!modelo&&!equipo?<div className="mt-3 space-y-2">{equipos.map(e=><button key={e.id} onClick={()=>setEquipo(e)} className="flex w-full justify-between rounded-xl border p-4 text-left hover:bg-green-50"><span><b>{e.marca} {e.modelo}</b><small className="block text-gray-500">{e.imei||"Sin IMEI"}</small></span><span className="text-green-700">Seleccionar</span></button>)}<button onClick={()=>setModelo(" ")} className="mt-2 text-sm font-bold text-green-700"><Plus size={15} className="inline"/> Nuevo equipo</button></div>:<div className="mt-3 grid gap-3 md:grid-cols-2"><input value={modelo} onChange={e=>setModelo(e.target.value)} placeholder="Modelo *" className="rounded-xl border px-4 py-3"/><input value={imei} onChange={e=>setImei(e.target.value)} placeholder="IMEI" className="rounded-xl border px-4 py-3"/></div>}
 <h2 className="mt-7 border-t pt-7 font-black">3. Servicio y repuestos</h2><input value={servicio} onChange={e=>setServicio(e.target.value)} placeholder="Ej: Cambio de batería / diagnóstico / reparación de placa" className="mt-3 w-full rounded-xl border px-4 py-3"/><div className="relative mt-3"><Search className="absolute left-3 top-3 text-gray-400" size={18}/><input value={pq} onChange={e=>setPq(e.target.value)} placeholder="Agregar repuesto del inventario..." className="h-11 w-full rounded-xl border pl-10"/>{pq&&<div className="absolute z-20 mt-1 w-full rounded-xl border bg-white p-2 shadow-xl">{pf.map(p=><button key={p.id} onClick={()=>add(p)} className="flex w-full justify-between rounded-lg p-3 text-left hover:bg-green-50"><span><b>{p.nombre}</b><small className="block text-gray-500">Stock: {p.stock_actual??0}</small></span><span>{money(Number(p.precio||0))}</span></button>)}</div>}</div><div className="mt-4 space-y-2">{lineas.map(l=><div key={l.producto_id} className="flex justify-between rounded-xl bg-gray-50 p-3 text-sm"><span>{l.nombre} × {l.cantidad}</span><span className="font-bold">{money(l.cantidad*l.precio)} <button onClick={()=>setLineas(lineas.filter(x=>x.producto_id!==l.producto_id))} className="ml-2 text-red-500"><Trash2 size={15} className="inline"/></button></span></div>)}</div><div className="mt-4 grid gap-3 md:grid-cols-2"><input value={mano} onChange={e=>setMano(e.target.value)} type="number" placeholder="Mano de obra (USD)" className="rounded-xl border px-4 py-3"/><select value={validez} onChange={e=>setValidez(e.target.value)} className="rounded-xl border px-4 py-3"><option>7 días</option><option>15 días</option><option>30 días</option></select></div>{error&&<div className="mt-5 rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</div>}<div className="mt-7 flex items-center justify-between border-t pt-6"><div><p className="text-xs text-gray-500">TOTAL</p><p className="text-3xl font-black">{money(total)}</p></div><button disabled={guardando} onClick={guardar} className="rounded-xl bg-green-600 px-6 py-3 font-bold text-white">{guardando?"Creando...":"Generar presupuesto"}</button></div></div></div></div></main>;
}