"use client";

import { useEffect, useMemo, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import {
  ArrowLeft, ArrowRight, Check, ClipboardCheck, FileText, Home,
  ImageIcon, Loader2, Package, Plus, Save, Smartphone, Trash2, User, Wrench,
} from "lucide-react";
import { supabase } from "../../../lib/supabase";

type Cliente = { nombre: string | null; telefono: string | null };
type Equipo = { marca:string|null; modelo:string|null; imei:string|null; numero_serie:string|null; color:string|null; capacidad:string|null; bateria_porcentaje:number|null };
type Orden = { id:number; taller_id:number|null; cliente_id:number|null; equipo_id:number|null; estado:string|null; falla_reportada:string|null; observaciones:string|null; created_at:string|null; presupuesto_mano_obra:number|null; cliente:Cliente|null; equipo:Equipo|null };
type Foto = { id:number; tipo:string; url:string };
type Producto = { id:number; nombre:string; categoria:string|null; marca:string|null; modelo:string|null; sku:string|null; costo:number|null; precio:number|null; stock_actual:number; activo:boolean };
type Item = { id:number; producto_id:number; cantidad:number; precio_unitario:number; costo_unitario:number; producto:Producto|null };
type Paso = { db:string; key:string; label:string };

const FLUJO:Paso[] = [
  {db:"RECIBIDO",key:"RECIBIDO",label:"Recibido"},
  {db:"DIAGNÓSTICO",key:"DIAGNOSTICO",label:"Diagnóstico"},
  {db:"PRESUPUESTADO",key:"PRESUPUESTADO",label:"Presupuesto"},
  {db:"ESPERANDO APROBACIÓN",key:"ESPERANDO APROBACION",label:"Esperando aprobación"},
  {db:"APROBADO",key:"APROBADO",label:"Aprobado"},
  {db:"EN REPARACIÓN",key:"EN REPARACION",label:"En reparación"},
  {db:"LISTO PARA ENTREGAR",key:"LISTO PARA ENTREGAR",label:"Listo para entregar"},
  {db:"ENTREGADO",key:"ENTREGADO",label:"Entregado"},
];

const normalizar=(v:string|null|undefined)=>(v||"").toUpperCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").trim();
const dinero=(n:number)=>new Intl.NumberFormat("es-AR",{style:"currency",currency:"USD",maximumFractionDigits:2}).format(Number(n)||0);
const estadoClase=(v:string|null|undefined)=>{switch(normalizar(v)){case"RECIBIDO":return"border-blue-200 bg-blue-50 text-blue-700";case"DIAGNOSTICO":return"border-purple-200 bg-purple-50 text-purple-700";case"PRESUPUESTADO":return"border-yellow-200 bg-yellow-50 text-yellow-700";case"ESPERANDO APROBACION":return"border-orange-200 bg-orange-50 text-orange-700";case"APROBADO":return"border-green-200 bg-green-50 text-green-700";case"EN REPARACION":return"border-indigo-200 bg-indigo-50 text-indigo-700";case"LISTO PARA ENTREGAR":return"border-emerald-200 bg-emerald-50 text-emerald-700";default:return"border-gray-200 bg-gray-100 text-gray-600";}};
const fecha=(v:string|null)=>v?new Date(v).toLocaleString("es-AR",{dateStyle:"short",timeStyle:"short"}):"-";

export default function ReparacionDetallePage(){
  const params=useParams(); const router=useRouter(); const ordenId=Number(params.id);
  const [orden,setOrden]=useState<Orden|null>(null),[fotos,setFotos]=useState<Foto[]>([]);
  const [diagnostico,setDiagnostico]=useState(""),[notas,setNotas]=useState("");
  const [productos,setProductos]=useState<Producto[]>([]),[items,setItems]=useState<Item[]>([]);
  const [productoId,setProductoId]=useState(""),[cantidad,setCantidad]=useState("1"),[precioVenta,setPrecioVenta]=useState(""),[busqueda,setBusqueda]=useState("");
  const [manoObra,setManoObra]=useState(""),[cargando,setCargando]=useState(true),[guardando,setGuardando]=useState(false),[error,setError]=useState(""),[mensaje,setMensaje]=useState("");

  const cargar=async()=>{
    setCargando(true);setError("");
    const {data,error:e}=await supabase.from("ordenes_reparacion").select(`id,taller_id,cliente_id,equipo_id,estado,falla_reportada,observaciones,created_at,presupuesto_mano_obra,clientes(nombre,telefono),equipos(marca,modelo,imei,numero_serie,color,capacidad,bateria_porcentaje)`).eq("id",ordenId).maybeSingle();
    if(e||!data){setError(e?.message||"La orden no existe.");setOrden(null);setCargando(false);return;}
    const cliente=Array.isArray(data.clientes)?data.clientes[0]||null:data.clientes||null; const equipo=Array.isArray(data.equipos)?data.equipos[0]||null:data.equipos||null;
    setOrden({...data,cliente,equipo} as Orden);
    const obs=data.observaciones||""; const dm=obs.match(/Diagnóstico:\s*([\s\S]*?)(?:\n\nNotas técnicas:|$)/i);const nm=obs.match(/Notas técnicas:\s*([\s\S]*)$/i);setDiagnostico(dm?.[1]?.trim()||"");setNotas(nm?.[1]?.trim()||(dm?"":obs));setManoObra(data.presupuesto_mano_obra!=null?String(data.presupuesto_mano_obra):"");
    const {data:fd}=await supabase.from("fotos_recepcion").select("id,tipo,url").eq("orden_id",ordenId).order("id");setFotos((fd||[]) as Foto[]);
    const {data:pd,error:pe}=await supabase.from("productos").select("id,nombre,categoria,marca,modelo,sku,costo,precio,stock_actual,activo").eq("taller_id",data.taller_id||1).eq("activo",true).order("nombre");
    if(!pe)setProductos((pd||[]) as Producto[]);
    const {data:id,error:ie}=await supabase.from("presupuesto_reparacion_items").select("id,producto_id,cantidad,precio_unitario,costo_unitario").eq("orden_id",ordenId).order("id");
    if(!ie){const lista=(id||[]) as Omit<Item,"producto">[];setItems(lista.map(x=>({...x,producto:(pd||[]).find((p:any)=>p.id===x.producto_id)||null})));}else if(!ie.message.includes("does not exist")){setError(`No se pudieron cargar los repuestos: ${ie.message}`);}
    setCargando(false);
  };
  useEffect(()=>{if(ordenId>0)void cargar();},[ordenId]);

  const posicion=useMemo(()=>{const k=normalizar(orden?.estado);const a:Record<string,string>={PRESUPUESTO:"PRESUPUESTADO","ESPERANDO REPUESTO":"ESPERANDO APROBACION",REPARADO:"LISTO PARA ENTREGAR"};return FLUJO.findIndex(p=>p.key===(a[k]||k));},[orden?.estado]);
  const siguiente=posicion>=0&&posicion<FLUJO.length-1?FLUJO[posicion+1]:null;
  const esPresupuesto=normalizar(orden?.estado)==="PRESUPUESTADO";
  const disponibles=useMemo(()=>{const q=busqueda.toLowerCase().trim();return productos.filter(p=>p.stock_actual>0&&(!q||[p.nombre,p.marca,p.modelo,p.categoria,p.sku].filter(Boolean).some(v=>String(v).toLowerCase().includes(q))));},[productos,busqueda]);
  const seleccionado=productos.find(p=>p.id===Number(productoId));
  useEffect(()=>{if(seleccionado)setPrecioVenta(String(seleccionado.precio??0));},[seleccionado]);

  const cambiarEstado=async(db:string)=>{if(!orden||guardando)return;setGuardando(true);setError("");setMensaje("");const{error:e}=await supabase.from("ordenes_reparacion").update({estado:db}).eq("id",orden.id);if(e)setError(e.message);else{setOrden({...orden,estado:db});setMensaje(`Estado actualizado a ${db}.`);}setGuardando(false);};
  const avanzar=async()=>{if(!siguiente||!orden)return;await cambiarEstado(siguiente.db);};
  const guardarNotas=async()=>{if(!orden)return;setGuardando(true);setError("");let observaciones=diagnostico.trim()?`Diagnóstico:\n${diagnostico.trim()}`:"";if(notas.trim())observaciones+=`${observaciones?"\n\n":""}Notas técnicas:\n${notas.trim()}`;const{error:e}=await supabase.from("ordenes_reparacion").update({observaciones}).eq("id",orden.id);if(e)setError(e.message);else{setOrden({...orden,observaciones});setMensaje("Diagnóstico y notas guardados.");}setGuardando(false);};

  const agregarRepuesto=async()=>{setError("");setMensaje("");const p=productos.find(x=>x.id===Number(productoId));const q=Number(cantidad);const precio=Number(precioVenta);if(!p)return setError("Seleccioná un repuesto del inventario.");if(!Number.isInteger(q)||q<=0)return setError("La cantidad debe ser mayor a 0.");if(!Number.isFinite(precio)||precio<0)return setError("Ingresá un precio válido.");const existente=items.find(x=>x.producto_id===p.id);const nueva=(existente?.cantidad||0)+q;if(nueva>p.stock_actual)return setError(`Stock insuficiente. ${p.nombre}: ${p.stock_actual} disponible(s).`);setGuardando(true);let e;if(existente){e=(await supabase.from("presupuesto_reparacion_items").update({cantidad:nueva,precio_unitario:precio}).eq("id",existente.id)).error;}else{e=(await supabase.from("presupuesto_reparacion_items").insert({orden_id:ordenId,producto_id:p.id,cantidad:q,costo_unitario:Number(p.costo||0),precio_unitario:precio})).error;}if(e)setError(`No se pudo guardar el repuesto: ${e.message}`);else{setMensaje(`${p.nombre} agregado al presupuesto.`);setProductoId("");setCantidad("1");setPrecioVenta("");setBusqueda("");await cargar();}setGuardando(false);};
  const eliminarRepuesto=async(id:number)=>{setGuardando(true);setError("");const{error:e}=await supabase.from("presupuesto_reparacion_items").delete().eq("id",id);if(e)setError(e.message);else setMensaje("Repuesto eliminado.");await cargar();setGuardando(false);};
  const guardarPresupuesto=async(enviar:boolean)=>{if(!orden)return;const mano=Math.max(0,Number(manoObra)||0);if(items.length===0&&mano<=0)return setError("Agregá al menos un repuesto o una mano de obra.");setGuardando(true);setError("");const{error:e}=await supabase.from("ordenes_reparacion").update({presupuesto_mano_obra:mano,estado:enviar?"ESPERANDO APROBACIÓN":"PRESUPUESTADO"}).eq("id",orden.id);if(e)setError(`No se pudo guardar el presupuesto: ${e.message}`);else{setOrden({...orden,presupuesto_mano_obra:mano,estado:enviar?"ESPERANDO APROBACIÓN":"PRESUPUESTADO"});setMensaje(enviar?"Presupuesto enviado a aprobación.":"Presupuesto guardado correctamente.");}setGuardando(false);};

  const totalRepuestos=items.reduce((s,i)=>s+Number(i.cantidad||0)*Number(i.precio_unitario||0),0),total=totalRepuestos+(Number(manoObra)||0);
  if(cargando)return <main className="min-h-screen bg-[#f5f6f8] flex items-center justify-center"><Loader2 size={32} className="animate-spin"/></main>;
  if(!orden)return <main className="min-h-screen bg-[#f5f6f8] p-8"><button onClick={()=>router.push("/reparaciones")} className="inline-flex items-center gap-2"><ArrowLeft size={17}/> Volver</button><div className="mt-6 rounded-2xl border border-red-200 bg-red-50 p-6 text-red-700">{error||"No se pudo cargar la reparación."}</div></main>;

  return <main className="min-h-screen bg-[#f5f6f8] text-gray-900"><div className="mx-auto max-w-[1500px] p-5 md:p-8">
    <div className="mb-6 flex flex-wrap items-center justify-between gap-3"><div className="flex gap-2"><button onClick={()=>router.push("/reparaciones")} className="inline-flex items-center gap-2 rounded-xl border border-gray-200 bg-white px-4 py-2.5 text-sm font-semibold shadow-sm"><ArrowLeft size={17}/> Volver</button><button onClick={()=>router.push("/")} className="inline-flex items-center gap-2 rounded-xl border border-gray-200 bg-white px-4 py-2.5 text-sm font-semibold shadow-sm"><Home size={17}/> Inicio</button></div><span className="text-xs font-semibold text-gray-400">Orden #{orden.id}</span></div>

    <section className="overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-sm"><div className="flex flex-col gap-5 p-6 md:p-8 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex flex-wrap items-center gap-3"><span className="rounded-full bg-gray-100 px-3 py-1 text-xs font-bold">ORDEN #{orden.id}</span><span className={`rounded-full border px-3 py-1 text-xs font-bold ${estadoClase(orden.estado)}`}>{FLUJO.find(p=>p.key===normalizar(orden.estado))?.label||orden.estado}</span></div><h1 className="mt-4 text-3xl font-bold tracking-tight md:text-4xl">Gestión de reparación</h1><p className="mt-2 text-sm text-gray-500">Diagnóstico, presupuesto, reparación y entrega.</p></div><div className="flex flex-wrap gap-2"><button onClick={()=>router.push(`/reparaciones/${orden.id}/checklist`)} className="inline-flex items-center gap-2 rounded-xl border px-4 py-3 text-sm font-semibold"><ClipboardCheck size={17}/> Checklist</button><button onClick={()=>router.push(`/reparaciones/${orden.id}/fotos`)} className="inline-flex items-center gap-2 rounded-xl border px-4 py-3 text-sm font-semibold"><ImageIcon size={17}/> Fotos</button><button onClick={()=>document.getElementById("presupuesto")?.scrollIntoView({behavior:"smooth"})} className="inline-flex items-center gap-2 rounded-xl bg-black px-4 py-3 text-sm font-semibold text-white"><Package size={17}/> Presupuesto</button></div></div>
      <div className="border-t bg-gray-50/70 p-6 md:p-8"><div className="overflow-x-auto"><div className="flex min-w-[950px] items-center">{FLUJO.map((p,i)=>{const activo=i===posicion,done=posicion>i;return <div key={p.key} className="flex flex-1 items-center"><button disabled={guardando} onClick={()=>cambiarEstado(p.db)} className="group flex min-w-0 flex-col items-center text-center"><div className={`flex h-9 w-9 items-center justify-center rounded-full border-2 text-xs font-bold ${activo?"border-black bg-black text-white":done?"border-green-500 bg-green-500 text-white":"border-gray-300 bg-white text-gray-400"}`}>{done?<Check size={16}/>:i+1}</div><span className={`mt-2 max-w-[115px] text-[10px] font-bold uppercase ${activo?"text-gray-950":done?"text-green-700":"text-gray-400"}`}>{p.label}</span></button>{i<FLUJO.length-1&&<div className={`mx-2 h-[2px] flex-1 ${done?"bg-green-400":"bg-gray-200"}`}/>}</div>})}</div></div><div className="mt-5 flex flex-wrap gap-3">{siguiente&&<button disabled={guardando} onClick={avanzar} className="inline-flex items-center gap-2 rounded-xl bg-black px-5 py-3 text-sm font-bold text-white">{guardando?<Loader2 size={17} className="animate-spin"/>:<ArrowRight size={17}/>} Avanzar a {siguiente.label}</button>}{(esPresupuesto||normalizar(orden.estado)==="DIAGNOSTICO")&&<button onClick={()=>document.getElementById("presupuesto")?.scrollIntoView({behavior:"smooth"})} className="inline-flex items-center gap-2 rounded-xl border border-gray-300 bg-white px-5 py-3 text-sm font-bold"><Package size={17}/> Cargar presupuesto</button>}</div></div></section>

    {mensaje&&<div className="mt-5 rounded-xl border border-green-200 bg-green-50 p-4 text-sm font-semibold text-green-700">{mensaje}</div>}{error&&<div className="mt-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm font-semibold text-red-700">{error}</div>}

    <div className="mt-6 grid gap-6 xl:grid-cols-[1.3fr_.7fr]"><div className="space-y-6">
      <section className="rounded-2xl border border-gray-200 bg-white shadow-sm"><div className="border-b border-gray-100 px-6 py-5"><div className="flex items-center gap-3"><div className="rounded-xl bg-gray-100 p-3"><Smartphone size={20}/></div><div><h2 className="text-lg font-bold">Cliente y equipo</h2><p className="text-xs text-gray-400">Información de la orden</p></div></div></div><div className="grid gap-5 p-6 md:grid-cols-2"><div className="rounded-xl bg-gray-50 p-5"><div className="flex items-center gap-2 text-xs font-bold uppercase text-gray-400"><User size={16}/> Cliente</div><p className="mt-3 text-lg font-bold">{orden.cliente?.nombre||"Sin nombre"}</p><p className="text-sm text-gray-500">{orden.cliente?.telefono||"Sin teléfono"}</p></div><div className="rounded-xl bg-gray-50 p-5"><div className="flex items-center gap-2 text-xs font-bold uppercase text-gray-400"><Smartphone size={16}/> Equipo</div><p className="mt-3 text-lg font-bold">{[orden.equipo?.marca,orden.equipo?.modelo].filter(Boolean).join(" ")||"Sin equipo"}</p><div className="mt-2 space-y-1 text-xs text-gray-500"><p>IMEI: {orden.equipo?.imei||"-"}</p><p>Serie: {orden.equipo?.numero_serie||"-"}</p><p>Color: {orden.equipo?.color||"-"}</p><p>Capacidad: {orden.equipo?.capacidad||"-"}</p><p>Batería: {orden.equipo?.bateria_porcentaje!=null?`${orden.equipo.bateria_porcentaje}%`:"-"}</p></div></div></div></section>
      <section className="rounded-2xl border border-gray-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><div className="rounded-xl bg-red-50 p-3"><Wrench size={20} className="text-red-600"/></div><div><h2 className="text-lg font-bold">Falla reportada</h2><p className="text-xs text-gray-400">Problema informado por el cliente</p></div></div><div className="mt-5 rounded-xl bg-gray-50 p-5 text-sm leading-6 text-gray-700 whitespace-pre-wrap">{orden.falla_reportada||"No se registró una falla reportada."}</div></section>
      <section className="rounded-2xl border border-gray-200 bg-white shadow-sm"><div className="border-b border-gray-100 px-6 py-5"><div className="flex items-center gap-3"><div className="rounded-xl bg-purple-50 p-3"><FileText size={20} className="text-purple-600"/></div><div><h2 className="text-lg font-bold">Diagnóstico y notas técnicas</h2><p className="text-xs text-gray-400">Información interna del técnico</p></div></div></div><div className="p-6"><label className="text-xs font-bold uppercase text-gray-400">Diagnóstico</label><textarea value={diagnostico} onChange={e=>setDiagnostico(e.target.value)} rows={5} className="mt-2 w-full resize-none rounded-xl border border-gray-200 bg-gray-50 px-4 py-3 text-sm outline-none focus:border-black focus:bg-white" placeholder="Qué se encontró al revisar el equipo..."/><label className="mt-5 block text-xs font-bold uppercase text-gray-400">Notas técnicas</label><textarea value={notas} onChange={e=>setNotas(e.target.value)} rows={5} className="mt-2 w-full resize-none rounded-xl border border-gray-200 bg-gray-50 px-4 py-3 text-sm outline-none focus:border-black focus:bg-white" placeholder="Mediciones, observaciones y trabajo a realizar..."/><div className="mt-4 flex justify-end"><button disabled={guardando} onClick={guardarNotas} className="inline-flex items-center gap-2 rounded-xl bg-black px-5 py-3 text-sm font-semibold text-white"><Save size={17}/> Guardar diagnóstico</button></div></div></section>

      <section id="presupuesto" className="scroll-mt-6 rounded-2xl border-2 border-gray-200 bg-white shadow-sm"><div className="border-b border-gray-100 bg-gray-50 p-6"><div className="flex items-center gap-3"><div className="rounded-xl bg-black p-3 text-white"><Package size={21}/></div><div><h2 className="text-xl font-bold">Presupuesto y repuestos</h2><p className="text-sm text-gray-500">Cargá acá mismo la mano de obra y los repuestos que se van a utilizar.</p></div></div></div><div className="p-6 space-y-6">
        <div className="rounded-xl border border-gray-200 p-5"><div className="grid gap-4 lg:grid-cols-[1fr_130px_150px_auto] lg:items-end"><div><label className="mb-2 block text-xs font-bold uppercase text-gray-400">Repuesto del inventario</label><input value={busqueda} onChange={e=>setBusqueda(e.target.value)} placeholder="Buscar repuesto..." className="mb-2 h-11 w-full rounded-xl border border-gray-200 bg-gray-50 px-4 text-sm outline-none focus:border-black"/><select value={productoId} onChange={e=>setProductoId(e.target.value)} className="h-11 w-full rounded-xl border border-gray-200 bg-white px-3 text-sm outline-none focus:border-black"><option value="">Seleccionar repuesto</option>{disponibles.map(p=><option key={p.id} value={p.id}>{p.nombre} · stock {p.stock_actual} · {dinero(Number(p.precio||0))}</option>)}</select></div><div><label className="mb-2 block text-xs font-bold uppercase text-gray-400">Cantidad</label><input type="number" min="1" value={cantidad} onChange={e=>setCantidad(e.target.value)} className="h-11 w-full rounded-xl border border-gray-200 px-4 text-sm"/></div><div><label className="mb-2 block text-xs font-bold uppercase text-gray-400">Precio venta</label><input type="number" min="0" step="0.01" value={precioVenta} onChange={e=>setPrecioVenta(e.target.value)} className="h-11 w-full rounded-xl border border-gray-200 px-4 text-sm"/></div><button disabled={guardando} onClick={agregarRepuesto} className="h-11 inline-flex items-center justify-center gap-2 rounded-xl bg-black px-5 text-sm font-bold text-white"><Plus size={17}/> Agregar</button></div>{disponibles.length===0&&<p className="mt-3 text-xs text-gray-500">No hay productos con stock disponible para esta búsqueda.</p>}</div>
        <div><h3 className="mb-3 text-sm font-bold uppercase tracking-wide text-gray-400">Repuestos incluidos</h3>{items.length===0?<div className="rounded-xl border border-dashed border-gray-300 p-6 text-center text-sm text-gray-400">Todavía no agregaste repuestos.</div>:<div className="overflow-hidden rounded-xl border border-gray-200"><div className="divide-y divide-gray-100">{items.map(i=><div key={i.id} className="flex flex-wrap items-center justify-between gap-3 p-4"><div><p className="font-bold">{i.producto?.nombre||`Producto #${i.producto_id}`}</p><p className="text-xs text-gray-500">{i.cantidad} × {dinero(i.precio_unitario)}</p></div><div className="flex items-center gap-4"><span className="font-bold">{dinero(i.cantidad*i.precio_unitario)}</span><button disabled={guardando} onClick={()=>eliminarRepuesto(i.id)} className="rounded-lg p-2 text-red-600 hover:bg-red-50"><Trash2 size={17}/></button></div></div>)}</div></div>}</div>
        <div className="grid gap-5 md:grid-cols-[1fr_260px]"><div className="rounded-xl border border-gray-200 p-5"><label className="text-xs font-bold uppercase text-gray-400">Mano de obra</label><div className="mt-2 flex gap-3"><input type="number" min="0" step="0.01" value={manoObra} onChange={e=>setManoObra(e.target.value)} placeholder="0.00" className="h-12 flex-1 rounded-xl border border-gray-200 px-4 text-sm"/><button disabled={guardando} onClick={()=>guardarPresupuesto(false)} className="inline-flex items-center gap-2 rounded-xl border px-4 text-sm font-bold"><Save size={16}/> Guardar</button></div></div><div className="rounded-xl bg-gray-950 p-5 text-white"><p className="text-xs font-bold uppercase text-gray-400">Total presupuesto</p><p className="mt-2 text-3xl font-bold">{dinero(total)}</p><p className="mt-1 text-xs text-gray-400">Repuestos {dinero(totalRepuestos)} + mano de obra {dinero(Number(manoObra)||0)}</p></div></div>
        <div className="flex flex-wrap justify-end gap-3 border-t pt-5"><button disabled={guardando} onClick={()=>guardarPresupuesto(false)} className="inline-flex items-center gap-2 rounded-xl border border-gray-300 bg-white px-5 py-3 text-sm font-bold"><Save size={17}/> Guardar presupuesto</button><button disabled={guardando} onClick={()=>guardarPresupuesto(true)} className="inline-flex items-center gap-2 rounded-xl bg-black px-5 py-3 text-sm font-bold text-white">{guardando?<Loader2 size={17} className="animate-spin"/>:<ArrowRight size={17}/>} Enviar a aprobación</button></div>
      </div></section>
    </div>

    <div className="space-y-6"><section className="rounded-2xl border border-gray-200 bg-white p-6 shadow-sm"><p className="text-xs font-bold uppercase tracking-[.14em] text-gray-400">Resumen</p><div className="mt-5 space-y-4"><div className="flex justify-between border-b pb-4"><span className="text-sm text-gray-500">Estado</span><span className={`rounded-full border px-3 py-1 text-xs font-bold ${estadoClase(orden.estado)}`}>{FLUJO.find(p=>p.key===normalizar(orden.estado))?.label||orden.estado}</span></div><div className="flex justify-between border-b pb-4"><span className="text-sm text-gray-500">Ingreso</span><span className="text-right text-xs font-semibold">{fecha(orden.created_at)}</span></div><div className="flex justify-between border-b pb-4"><span className="text-sm text-gray-500">Fotos</span><span className="font-bold">{fotos.length}</span></div><div className="flex justify-between"><span className="text-sm text-gray-500">Total</span><span className="font-bold">{dinero(total)}</span></div></div></section>
      {fotos.length>0&&<section className="rounded-2xl border border-gray-200 bg-white p-6 shadow-sm"><div className="flex justify-between"><div><h2 className="font-bold">Fotografías</h2><p className="text-xs text-gray-400">Fotos de recepción</p></div><span className="rounded-full bg-gray-100 px-3 py-1 text-xs font-bold">{fotos.length}</span></div><div className="mt-5 grid grid-cols-2 gap-3">{fotos.slice(0,6).map(f=><img key={f.id} src={f.url} alt={f.tipo} className="aspect-square w-full rounded-xl border object-cover"/>)}</div></section>}
      <section className="rounded-2xl bg-gray-950 p-6 text-white shadow-sm"><p className="text-xs font-bold uppercase tracking-[.14em] text-gray-400">Próximo paso</p><h2 className="mt-3 text-xl font-bold">{siguiente?siguiente.label:"Reparación finalizada"}</h2><p className="mt-2 text-sm leading-6 text-gray-400">{siguiente?"Completá la tarea actual y avanzá la orden al siguiente estado.":"Esta orden llegó al último estado."}</p>{siguiente&&<button disabled={guardando} onClick={avanzar} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl bg-white px-4 py-3 text-sm font-bold text-gray-950"><ArrowRight size={17}/> Avanzar reparación</button>}</section></div></div>
    <div className="py-8 text-center text-[11px] font-semibold tracking-wide text-gray-400">BITFIX TALLER · Gestión de reparación</div>
  </div></main>;
}
