-- Presupuesto de reparaciones
-- Ejecutar este archivo una sola vez en Supabase SQL Editor.

ALTER TABLE ordenes_reparacion
  ADD COLUMN IF NOT EXISTS presupuesto_mano_obra numeric(12,2) NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS presupuesto_reparacion_items (
  id bigint generated by default as identity primary key,
  taller_id bigint NOT NULL DEFAULT 1,
  orden_id bigint NOT NULL REFERENCES ordenes_reparacion(id) ON DELETE CASCADE,
  producto_id bigint NOT NULL REFERENCES productos(id) ON DELETE RESTRICT,
  cantidad integer NOT NULL CHECK (cantidad > 0),
  costo_unitario numeric(12,2) NOT NULL DEFAULT 0,
  precio_unitario numeric(12,2) NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (orden_id, producto_id)
);

CREATE INDEX IF NOT EXISTS idx_presupuesto_reparacion_items_orden
  ON presupuesto_reparacion_items(orden_id);

CREATE INDEX IF NOT EXISTS idx_presupuesto_reparacion_items_producto
  ON presupuesto_reparacion_items(producto_id);

ALTER TABLE presupuesto_reparacion_items ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "presupuesto_reparacion_items_all" ON presupuesto_reparacion_items;
CREATE POLICY "presupuesto_reparacion_items_all"
  ON presupuesto_reparacion_items
  FOR ALL
  USING (true)
  WITH CHECK (true);


-- Garantizar nombre_producto desde el inventario.
ALTER TABLE public.presupuesto_reparacion_items
  ADD COLUMN IF NOT EXISTS nombre_producto text;

UPDATE public.presupuesto_reparacion_items i
SET nombre_producto = p.nombre
FROM public.productos p
WHERE p.id = i.producto_id
  AND (i.nombre_producto IS NULL OR btrim(i.nombre_producto) = '');

CREATE OR REPLACE FUNCTION public.set_presupuesto_reparacion_item_nombre()
RETURNS trigger
LANGUAGE plpgsql
AS $
BEGIN
  IF NEW.nombre_producto IS NULL OR btrim(NEW.nombre_producto) = '' THEN
    SELECT p.nombre INTO NEW.nombre_producto
    FROM public.productos p
    WHERE p.id = NEW.producto_id;
  END IF;

  IF NEW.nombre_producto IS NULL OR btrim(NEW.nombre_producto) = '' THEN
    RAISE EXCEPTION 'El producto seleccionado no tiene nombre en inventario';
  END IF;

  RETURN NEW;
END;
$;

DROP TRIGGER IF EXISTS trg_presupuesto_reparacion_item_nombre
ON public.presupuesto_reparacion_items;

CREATE TRIGGER trg_presupuesto_reparacion_item_nombre
BEFORE INSERT OR UPDATE OF producto_id, nombre_producto
ON public.presupuesto_reparacion_items
FOR EACH ROW
EXECUTE FUNCTION public.set_presupuesto_reparacion_item_nombre();

ALTER TABLE public.presupuesto_reparacion_items
  ALTER COLUMN nombre_producto SET NOT NULL;

-- Estados definitivos del flujo.
ALTER TABLE ordenes_reparacion
DROP CONSTRAINT IF EXISTS ordenes_reparacion_estado_check;

ALTER TABLE ordenes_reparacion
ADD CONSTRAINT ordenes_reparacion_estado_check
CHECK (
  estado = ANY (ARRAY[
    'RECIBIDO'::text,
    'DIAGNÓSTICO'::text,
    'PRESUPUESTADO'::text,
    'ESPERANDO APROBACIÓN'::text,
    'APROBADO'::text,
    'EN REPARACIÓN'::text,
    'LISTO PARA ENTREGAR'::text,
    'ENTREGADO'::text,
    'CANCELADO'::text,
    -- Compatibilidad temporal con datos/código anteriores
    'DIAGNOSTICO'::text,
    'PRESUPUESTO'::text,
    'ESPERANDO REPUESTO'::text,
    'EN REPARACION'::text,
    'REPARADO'::text
  ])
);
