-- Presupuesto de reparaciones
-- Ejecutar este archivo una sola vez en Supabase SQL Editor.

ALTER TABLE ordenes_reparacion
  ADD COLUMN IF NOT EXISTS presupuesto_mano_obra numeric(12,2) NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS presupuesto_reparacion_items (
  id bigint generated by default as identity primary key,
  taller_id bigint NOT NULL DEFAULT 1,
  orden_id bigint NOT NULL REFERENCES ordenes_reparacion(id) ON DELETE CASCADE,
  producto_id bigint NOT NULL REFERENCES productos(id) ON DELETE RESTRICT,
  cantidad integer NOT NULL CHECK (cantidad > 0),
  costo_unitario numeric(12,2) NOT NULL DEFAULT 0,
  precio_unitario numeric(12,2) NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (orden_id, producto_id)
);

CREATE INDEX IF NOT EXISTS idx_presupuesto_reparacion_items_orden
  ON presupuesto_reparacion_items(orden_id);

CREATE INDEX IF NOT EXISTS idx_presupuesto_reparacion_items_producto
  ON presupuesto_reparacion_items(producto_id);

ALTER TABLE presupuesto_reparacion_items ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "presupuesto_reparacion_items_all" ON presupuesto_reparacion_items;
CREATE POLICY "presupuesto_reparacion_items_all"
  ON presupuesto_reparacion_items
  FOR ALL
  USING (true)
  WITH CHECK (true);

-- Estados definitivos del flujo.
ALTER TABLE ordenes_reparacion
DROP CONSTRAINT IF EXISTS ordenes_reparacion_estado_check;

ALTER TABLE ordenes_reparacion
ADD CONSTRAINT ordenes_reparacion_estado_check
CHECK (
  estado = ANY (ARRAY[
    'RECIBIDO'::text,
    'DIAGNÓSTICO'::text,
    'PRESUPUESTADO'::text,
    'ESPERANDO APROBACIÓN'::text,
    'APROBADO'::text,
    'EN REPARACIÓN'::text,
    'LISTO PARA ENTREGAR'::text,
    'ENTREGADO'::text,
    'CANCELADO'::text,
    -- Compatibilidad temporal con datos/código anteriores
    'DIAGNOSTICO'::text,
    'PRESUPUESTO'::text,
    'ESPERANDO REPUESTO'::text,
    'EN REPARACION'::text,
    'REPARADO'::text
  ])
);
