-- Ventas de equipos (iPhone nuevos/usados)
-- Ejecutar en Supabase SQL Editor una sola vez.

CREATE TABLE IF NOT EXISTS public.ventas_equipos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  taller_id bigint NOT NULL DEFAULT 1,
  venta_id bigint NULL REFERENCES public.ventas(id) ON DELETE SET NULL,
  producto_id bigint NOT NULL REFERENCES public.productos(id) ON DELETE RESTRICT,
  cliente_id bigint NULL REFERENCES public.clientes(id) ON DELETE SET NULL,
  marca text NOT NULL DEFAULT 'Apple',
  modelo text NOT NULL,
  capacidad text NULL,
  color text NULL,
  imei text NULL,
  numero_serie text NULL,
  salud_bateria numeric(5,2) NULL,
  condicion text NOT NULL DEFAULT 'USADO',
  estado_fisico text NULL,
  garantia_dias integer NOT NULL DEFAULT 60,
  costo_usd numeric(12,2) NOT NULL DEFAULT 0,
  precio_usd numeric(12,2) NOT NULL DEFAULT 0,
  ganancia_usd numeric(12,2) NOT NULL DEFAULT 0,
  observaciones text NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ventas_equipos_taller_idx ON public.ventas_equipos(taller_id);
CREATE INDEX IF NOT EXISTS ventas_equipos_imei_idx ON public.ventas_equipos(imei);
CREATE INDEX IF NOT EXISTS ventas_equipos_serie_idx ON public.ventas_equipos(numero_serie);

ALTER TABLE public.ventas_equipos ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "ventas_equipos_anon_select" ON public.ventas_equipos;
DROP POLICY IF EXISTS "ventas_equipos_anon_insert" ON public.ventas_equipos;

CREATE POLICY "ventas_equipos_anon_select"
ON public.ventas_equipos FOR SELECT
USING (true);

CREATE POLICY "ventas_equipos_anon_insert"
ON public.ventas_equipos FOR INSERT
WITH CHECK (true);
