-- Talleres: base para flujo completo de reparaciones
-- Ejecutar una sola vez en Supabase SQL Editor.

ALTER TABLE public.ordenes_reparacion
  ADD COLUMN IF NOT EXISTS tecnico_id uuid REFERENCES public.perfiles(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS garantia_dias integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS garantia_hasta timestamptz,
  ADD COLUMN IF NOT EXISTS entregado_at timestamptz;

CREATE INDEX IF NOT EXISTS idx_ordenes_reparacion_tecnico
  ON public.ordenes_reparacion(tecnico_id);

CREATE TABLE IF NOT EXISTS public.historial_reparacion (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  orden_id bigint NOT NULL REFERENCES public.ordenes_reparacion(id) ON DELETE CASCADE,
  usuario_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  tipo text NOT NULL DEFAULT 'ESTADO',
  estado_anterior text,
  estado_nuevo text,
  descripcion text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_historial_reparacion_orden
  ON public.historial_reparacion(orden_id, created_at DESC);

ALTER TABLE public.historial_reparacion ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS historial_reparacion_select ON public.historial_reparacion;
DROP POLICY IF EXISTS historial_reparacion_insert ON public.historial_reparacion;

CREATE POLICY historial_reparacion_select
  ON public.historial_reparacion FOR SELECT TO authenticated
  USING (true);

CREATE POLICY historial_reparacion_insert
  ON public.historial_reparacion FOR INSERT TO authenticated
  WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public.pagos_reparacion (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  taller_id bigint NOT NULL DEFAULT 1,
  orden_id bigint NOT NULL REFERENCES public.ordenes_reparacion(id) ON DELETE CASCADE,
  monto numeric(12,2) NOT NULL CHECK (monto > 0),
  metodo_pago text NOT NULL DEFAULT 'EFECTIVO',
  observaciones text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_pagos_reparacion_orden
  ON public.pagos_reparacion(orden_id, created_at DESC);

ALTER TABLE public.pagos_reparacion ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS pagos_reparacion_all ON public.pagos_reparacion;
CREATE POLICY pagos_reparacion_all
  ON public.pagos_reparacion FOR ALL TO authenticated
  USING (true) WITH CHECK (true);

CREATE OR REPLACE FUNCTION public.registrar_historial_reparacion(
  p_orden_id bigint,
  p_tipo text,
  p_estado_anterior text,
  p_estado_nuevo text,
  p_descripcion text DEFAULT NULL
)
RETURNS public.historial_reparacion
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE v_result public.historial_reparacion;
BEGIN
  INSERT INTO public.historial_reparacion(
    orden_id, usuario_id, tipo, estado_anterior, estado_nuevo, descripcion
  ) VALUES (
    p_orden_id, auth.uid(), COALESCE(p_tipo,'ESTADO'),
    p_estado_anterior, p_estado_nuevo, p_descripcion
  ) RETURNING * INTO v_result;
  RETURN v_result;
END;
$$;

GRANT EXECUTE ON FUNCTION public.registrar_historial_reparacion(bigint,text,text,text,text) TO authenticated;
