-- Presupuestos independientes
CREATE TABLE IF NOT EXISTS public.presupuestos_independientes (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 taller_id bigint NOT NULL DEFAULT 1,
 cliente_id bigint NOT NULL REFERENCES public.clientes(id) ON DELETE RESTRICT,
 equipo_id bigint REFERENCES public.equipos(id) ON DELETE SET NULL,
 servicio text,
 mano_obra numeric(12,2) NOT NULL DEFAULT 0,
 validez text NOT NULL DEFAULT '7 días',
 validez_dias integer NOT NULL DEFAULT 7,
 total numeric(12,2) NOT NULL DEFAULT 0,
 estado text NOT NULL DEFAULT 'PENDIENTE',
 created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.presupuestos_independientes_items (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 presupuesto_id bigint NOT NULL REFERENCES public.presupuestos_independientes(id) ON DELETE CASCADE,
 producto_id bigint NOT NULL REFERENCES public.productos(id) ON DELETE RESTRICT,
 nombre_producto text NOT NULL,
 cantidad integer NOT NULL CHECK(cantidad>0),
 precio_unitario numeric(12,2) NOT NULL DEFAULT 0,
 costo_unitario numeric(12,2) NOT NULL DEFAULT 0
);
ALTER TABLE public.presupuestos_independientes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.presupuestos_independientes_items ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS presupuestos_independientes_all ON public.presupuestos_independientes;
DROP POLICY IF EXISTS presupuestos_independientes_items_all ON public.presupuestos_independientes_items;
CREATE POLICY presupuestos_independientes_all ON public.presupuestos_independientes FOR ALL USING(true) WITH CHECK(true);
CREATE POLICY presupuestos_independientes_items_all ON public.presupuestos_independientes_items FOR ALL USING(true) WITH CHECK(true);