-- TALLERES - VENTA DE EQUIPOS
CREATE TABLE IF NOT EXISTS public.equipos_venta (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  taller_id bigint NOT NULL DEFAULT 1,
  marca text NOT NULL,
  modelo text NOT NULL,
  capacidad text,
  color text,
  tipo text NOT NULL DEFAULT 'USADO' CHECK (tipo IN ('NUEVO','USADO')),
  imei text,
  numero_serie text,
  salud_bateria numeric(5,2),
  estado_estetico text,
  costo numeric(12,2) NOT NULL DEFAULT 0,
  precio numeric(12,2) NOT NULL DEFAULT 0,
  garantia_dias integer NOT NULL DEFAULT 30,
  observaciones text,
  image_url text,
  estado text NOT NULL DEFAULT 'DISPONIBLE'
    CHECK (estado IN ('DISPONIBLE','RESERVADO','VENDIDO','BAJA')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS equipos_venta_taller_imei_unique
ON public.equipos_venta(taller_id, imei)
WHERE imei IS NOT NULL AND imei <> '';

CREATE INDEX IF NOT EXISTS equipos_venta_taller_estado_idx
ON public.equipos_venta(taller_id, estado);

ALTER TABLE public.ventas
  ADD COLUMN IF NOT EXISTS tipo_venta text NOT NULL DEFAULT 'PRODUCTO';

ALTER TABLE public.venta_detalles
  ALTER COLUMN producto_id DROP NOT NULL;

ALTER TABLE public.venta_detalles
  ADD COLUMN IF NOT EXISTS equipo_venta_id bigint REFERENCES public.equipos_venta(id) ON DELETE RESTRICT;

CREATE INDEX IF NOT EXISTS venta_detalles_equipo_venta_idx
ON public.venta_detalles(equipo_venta_id);

ALTER TABLE public.equipos_venta ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "equipos_venta_anon_select" ON public.equipos_venta;
DROP POLICY IF EXISTS "equipos_venta_anon_insert" ON public.equipos_venta;
DROP POLICY IF EXISTS "equipos_venta_anon_update" ON public.equipos_venta;
DROP POLICY IF EXISTS "equipos_venta_anon_delete" ON public.equipos_venta;

CREATE POLICY "equipos_venta_anon_select" ON public.equipos_venta FOR SELECT TO anon USING (true);
CREATE POLICY "equipos_venta_anon_insert" ON public.equipos_venta FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY "equipos_venta_anon_update" ON public.equipos_venta FOR UPDATE TO anon USING (true) WITH CHECK (true);
CREATE POLICY "equipos_venta_anon_delete" ON public.equipos_venta FOR DELETE TO anon USING (true);

CREATE OR REPLACE FUNCTION public.registrar_venta_equipo(
  p_taller_id bigint,
  p_equipo_id bigint,
  p_cliente_id bigint DEFAULT NULL,
  p_metodo_pago text DEFAULT 'EFECTIVO',
  p_descuento numeric DEFAULT 0,
  p_observaciones text DEFAULT NULL
)
RETURNS bigint
LANGUAGE plpgsql
AS $$
DECLARE
  v_equipo public.equipos_venta%ROWTYPE;
  v_venta_id bigint;
  v_total numeric(12,2);
  v_ganancia numeric(12,2);
BEGIN
  SELECT * INTO v_equipo
  FROM public.equipos_venta
  WHERE id = p_equipo_id AND taller_id = p_taller_id
  FOR UPDATE;

  IF NOT FOUND THEN RAISE EXCEPTION 'Equipo no encontrado'; END IF;
  IF v_equipo.estado <> 'DISPONIBLE' THEN RAISE EXCEPTION 'El equipo no está disponible para la venta'; END IF;
  IF COALESCE(v_equipo.precio,0) <= 0 THEN RAISE EXCEPTION 'El equipo no tiene un precio de venta válido'; END IF;

  v_total := GREATEST(v_equipo.precio - GREATEST(COALESCE(p_descuento,0),0), 0);
  v_ganancia := v_total - COALESCE(v_equipo.costo,0);

  INSERT INTO public.ventas (
    taller_id, cliente_id, subtotal, descuento, total, ganancia,
    metodo_pago, estado, observaciones, tipo_venta
  ) VALUES (
    p_taller_id, p_cliente_id, v_equipo.precio,
    GREATEST(COALESCE(p_descuento,0),0), v_total, v_ganancia,
    p_metodo_pago, 'COMPLETADA', p_observaciones, 'EQUIPO'
  ) RETURNING id INTO v_venta_id;

  INSERT INTO public.venta_detalles (
    venta_id, producto_id, equipo_venta_id, producto_nombre,
    cantidad, costo_unitario, precio_unitario, subtotal, ganancia
  ) VALUES (
    v_venta_id, NULL, v_equipo.id,
    concat_ws(' ', v_equipo.marca, v_equipo.modelo, v_equipo.capacidad),
    1, v_equipo.costo, v_equipo.precio, v_total, v_ganancia
  );

  UPDATE public.equipos_venta
  SET estado = 'VENDIDO', updated_at = now()
  WHERE id = v_equipo.id;

  RETURN v_venta_id;
END;
$$;

GRANT EXECUTE ON FUNCTION public.registrar_venta_equipo(bigint,bigint,bigint,text,numeric,text) TO anon;
