-- Control financiero: caja, bancos y cuenta corriente
create table if not exists public.movimientos_caja (
  id bigint generated by default as identity primary key,
  taller_id bigint not null default 1,
  tipo text not null check (tipo in ('INGRESO','EGRESO')),
  medio text not null check (medio in ('EFECTIVO','BANCO','MERCADO_PAGO','OTRO')),
  monto numeric(14,2) not null check (monto > 0),
  concepto text not null,
  cliente_id bigint null references public.clientes(id) on delete set null,
  venta_id bigint null references public.ventas(id) on delete set null,
  orden_id bigint null references public.ordenes_reparacion(id) on delete set null,
  created_at timestamptz not null default now()
);
create index if not exists movimientos_caja_taller_fecha_idx on public.movimientos_caja(taller_id,created_at desc);

create table if not exists public.cuentas_corrientes (
  id bigint generated by default as identity primary key,
  taller_id bigint not null default 1,
  cliente_id bigint not null references public.clientes(id) on delete cascade,
  tipo text not null check (tipo in ('CARGO','PAGO')),
  monto numeric(14,2) not null check (monto > 0),
  concepto text not null,
  medio text null,
  venta_id bigint null references public.ventas(id) on delete set null,
  orden_id bigint null references public.ordenes_reparacion(id) on delete set null,
  created_at timestamptz not null default now()
);
create index if not exists cuentas_corrientes_taller_cliente_idx on public.cuentas_corrientes(taller_id,cliente_id,created_at desc);

alter table public.movimientos_caja enable row level security;
alter table public.cuentas_corrientes enable row level security;
create policy "taller movimientos caja" on public.movimientos_caja for all using (taller_id = 1) with check (taller_id = 1);
create policy "taller cuentas corrientes" on public.cuentas_corrientes for all using (taller_id = 1) with check (taller_id = 1);
